# config/packages/knp_paginator.yaml

knp_paginator:
    page_range: 5              # Nombre de pages affichées dans la barre de pagination
    default_options:
        page_name: page        # Nom du paramètre de la page dans l'URL (ex. /page/2)
        sort_field_name: sort  # Nom du paramètre pour le tri dans l'URL (ex. /sort/name)
        sort_direction_name: direction # Nom du paramètre pour la direction de tri dans l'URL (ex. /direction/asc)
        distinct: true         # Pour la pagination DISTINCT (doit être vrai si votre requête utilise DISTINCT)